//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventarios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Id_Empleado { get; set; }
        public string Nombre { get; set; }
        public string Rfc { get; set; }
        public int Salario { get; set; }
        public System.DateTime Fecha_Dacimiento { get; set; }
    }
}
